language: java
install:
  - gradle wrapper
jobs:
  include:
    - stage: "compile with different Java versions"
      jdk:
      - openjdk8
    - jdk:
      - openjdk12
    - stage: "Upload to Wiki"
      jdk:
      - openjdk8
      script:
        - ./saveJAR.sh
      if: (branch = master) AND (type = push)