language: java
jobs:
  include:
    - stage: "Upload to Wiki"
      jdk:
      - openjdk8
      before_install:
      - gradle wrapper
      script:
        - chmod +x ./saveJAR.sh
        - ./saveJAR.sh
      #if: branch = master