name: static code analysis
on: [push]
jobs:
  Spotbugs-8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn spotbugs:check
  Spotbugs-13:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: Build with Maven
      run: mvn spotbugs:check
  SonarCloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup sonarqube
        uses: warchant/setup-sonar-scanner@v1
      - name: compile
        run: mvn install -DskipTests=true
      - name: Run sonarqube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: sonar-scanner
             -Dsonar.login=$SONAR_TOKEN
             -Dsonar.organization=nightdream
             -Dsonar.host.url=https://sonarcloud.io/
             -Dsonar.projectKey=NightDream
             -Dsonar.sources=src/
             -Dsonar.java.binaries=target/classes
             -Dsonar.java.libraries=target/classes
