name: static code analysis
on: [push]
jobs:
  Spotbugs-8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn spotbugs:check
  Spotbugs-12:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn spotbugs:check
  SonarCloud:
    runs-on: ubuntu-latest
    steps:
      - name: Setup sonarqube
        uses: warchant/setup-sonar-scanner@v1
      - name: Run sonarqube
        env:
          # to get access to secrets.SONAR_TOKEN, provide GITHUB_TOKEN
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: sonar-scanner
             -Dsonar.login=$SONAR_TOKEN
             -Dsonar.organization=nightdream
             -Dsonar.host.url=https://sonarcloud.io/
             -Dsonar.projectKey=JDiscordBots_NightDream-Logging
