name: test and upload
on: [push]
jobs:
  compile-8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: "compile with Java 8"
      run: mvn -B test-compile
  compile-13:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: "compile with Java 13"
      run: mvn -B test-compile
  test:
    strategy:
      max-parallel: 1
    runs-on: ubuntu-latest
    needs: compile-8
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: "setup files"
      run: |
        echo "jda-factory-class=io.github.jdiscordbots.nightdream.JDALoader" > $propFile;
        echo "jda-factory-method=load" >> $propFile
        echo "testing-prefix=nt." >> $propFile
        echo "testing-channel=$testChan" >> $propFile
        mkdir test
        echo "prefix=nt." >> test/Guild.properties
        echo "KSoftToken=$kSoftToken" >> test/NightDream.properties
        echo "PixabayAPIKey=$pixabayAPIKey" >> test/NightDream.properties
      env:
        testChan: ${{ secrets.testingChannel }}
        propFile:  src/test/resources/jda-tests.properties
        kSoftToken: ${{ secrets.ksoftToken }}
        pixabayAPIKey: ${{ secrets.pixabayAPIKey }}
    - name: "automated (feature) tests"
      run: "mvn -B -Dio.github.jdiscordbots.nightdream.logging.Level.io.github.jdiscordbots.jdatesting.TestUtils=DEBUG test"
      env:
        ND_token: ${{secrets.botToken}}
        ND_admin: ${{secrets.botAdmin}}
        ND_testuser: ${{secrets.testUser}}
  upload:
    runs-on: ubuntu-latest
    needs: [compile-8,compile-13,test]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: "setup user info"
        run: |
          git config --global user.email "CI@github.com"
          git config --global user.name "CI"
      - name: "clone Wiki"
        run: git clone https://github.com/JDiscordBots/NightDream.wiki.git wiki
      - name: "create JAR and copy it to the wiki"
        run: |
          mvn package -DskipTests=true
          cp target/NightDream.jar wiki/NightDream.jar
      - name: "Upload to wiki"
        run: |
          cd wiki
          git add NightDream.jar
          git commit -m "CI JAR deploy: `date`"
          git push https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/JDiscordBots/NightDream.wiki.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
