on: repository_dispatch
  types: [update_notice]
name: Update NOTICE.md
jobs:
  updateNotice:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
       java-version: 1.8
    - name: "generate notice"
      # create file if changes occur
      run: mvn -B notice:generate
    - id: checkNotice
      name: "check notice "
      # 1 if changes
      run: "echo ::set-output name=hasUpdates::$(git diff --exit-code>/dev/null;echo $?)"
    - name: "setup git"
      run: |
        git remote add github https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
        git pull github ${GITHUB_REF} --ff-only
        git config --global user.name "github-actions-bot"
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: steps.checkNotice.outputs.hasUpdates != '0'
    - name: commit
      run: |
        git add pom.xml
        git commit -m "update Notice"
      if: steps.checkNotice.outputs.hasUpdates != '0'
    - name: push
      run: git push github HEAD:${GITHUB_REF}
      if: steps.checkNotice.outputs.hasUpdates != '0'
